package com.syrianvcg.vcg;

import java.nio.file.Path;

/**
 * Produces a plain, static HTML report of a program's output.
 * Unlike the old SDK, this contains NO embedded JavaScript interpreter —
 * the VCG program already ran natively on the JVM; this file is just a
 * pretty static rendering of what it printed/emitted.
 */
public final class HtmlReport {
    private HtmlReport() {}

    public static String render(OutputSink sink, String sourcePath) {
        String title = Path.of(sourcePath).getFileName().toString();
        StringBuilder body = new StringBuilder();
        if (sink.entries().isEmpty()) {
            body.append("<p class='empty'>لا يوجد مخرجات / No output</p>");
        } else {
            for (OutputSink.Entry e : sink.entries()) {
                if (e.kind == OutputSink.Kind.HTML) {
                    body.append("<div class='html-block'>").append(e.value).append("</div>\n");
                } else {
                    body.append("<div class='line'>").append(escape(e.value)).append("</div>\n");
                }
            }
        }

        return "<!DOCTYPE html>\n" +
            "<html lang='ar' dir='rtl'>\n" +
            "<head>\n" +
            "<meta charset='UTF-8'>\n" +
            "<meta name='viewport' content='width=device-width,initial-scale=1'>\n" +
            "<title>" + escape(title) + " — VCG Output</title>\n" +
            "<style>\n" +
            "body{background:#0d1320;color:#eaf2ff;font-family:'Cairo',system-ui,sans-serif;padding:1.2rem;line-height:1.8}\n" +
            "#out{font-family:'JetBrains Mono',monospace;font-size:0.9rem}\n" +
            ".line{padding:0.15rem 0.4rem;border-radius:4px}\n" +
            ".line:hover{background:rgba(127,127,127,0.08)}\n" +
            ".html-block{margin:0.5rem 0}\n" +
            ".empty{color:#7f93b3;font-style:italic}\n" +
            "h1{color:#4da65a;border-bottom:2px solid #1c2433;padding-bottom:0.3rem}\n" +
            "</style>\n" +
            "</head>\n" +
            "<body>\n" +
            "<h1>" + escape(title) + "</h1>\n" +
            "<div id='out'>\n" + body + "</div>\n" +
            "<p style='color:#7f93b3;font-size:0.8rem;margin-top:2rem'>Generated by the native VCG Java interpreter (no embedded JS runtime).</p>\n" +
            "</body>\n" +
            "</html>";
    }

    private static String escape(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
