package com.syrianvcg.vcg;

public enum TokenType {
    // Literals
    NUMBER, STRING, IDENT, TRUE, FALSE, NIL,

    // Keywords
    LET, CONST, W, FUNC, RETURN, IF, ELSE, WHILE, FOR, IN, REPEAT,
    MATCH, WHEN, CLASS, EXTENDS, NEW, SELF, MODULE, FROM, IMPORT,
    ENUM, TRY, CATCH, THROW, SAFE, UNSAFE, GUARD, TEST, ASSERT,
    BREAK, CONTINUE, ASYNC, AWAIT, TYPE, STRUCT, AND, OR, NOT,
    SEAL, PRINT, SHOW, HTML, PATTERN, RENDER, C_CHANNEL,

    // Symbols
    PLUS, MINUS, STAR, SLASH, PERCENT, POW,
    EQ, NEQ, LT, GT, LE, GE,
    ASSIGN, PLUS_EQ, MINUS_EQ, STAR_EQ, SLASH_EQ,
    LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET,
    COMMA, COLON, DOT, DOTDOT, ARROW, FATARROW, QUESTION,
    PIPE, AMP, SHL, SHR, BACKSLASH, SEMI,

    NEWLINE, EOF
}
